 테이블에 샘플 데이터를  추가 : 1000개
 

-- 데이터를 1000개 추가한다.
DECLARE 
    DATA1 VARCHAR2(100) := 'HTML 게시물!! ';
    
BEGIN
    FOR I IN 12 .. 1000
    LOOP
        INSERT INTO BOARD(BNO, MENU_ID,TITLE,CONTENT,WRITER,REGDATE,HIT)
        VALUES           (I,'MENU01',DATA1 || I,'내용','admin',SYSDATE,0);
    END LOOP;
    COMMIT;
END;



--2. ROW_NUMBER() 사용
SET TIMING ON
SELECT *
FROM (
SELECT  ROW_NUMBER() OVER (ORDER BY BNO DESC) RN, BNO, MENU_ID,TITLE,CONTENT,WRITER,REGDATE,HIT
FROM    BOARD) T
WHERE T.RN BETWEEN 51 AND 70;



--3.OFFSET .. FETCH ..
SET TIMING ON
SELECT  BNO, 
        MENU_ID,
        TITLE,
        CONTENT,
        WRITER,
        TO_CHAR(REGDATE, 'YYYY-MM-DD') REGDATE,
        HIT
FROM BOARD
ORDER BY BNO DESC
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;